name: PowerRanks
version: 1.9.4 BETA 1
main: nl.svenar.PowerRanks.PowerRanks
api-version: 1.13
authors: [svenar_nl]
softdepend: [Vault, PlaceholderAPI, DeluxeTags, NametagEdit]
load: startup
website: 'https://powerranks.nl'
commands:
  powerranks:
    description: Main Command
  pr:
    description: Main Command
permissions:
  powerranks.cmd.help:
    default: true
  powerranks.cmd.reload:
    default: op
  powerranks.cmd.setrank:
    default: op
  powerranks.cmd.setownrank:
    default: op
  powerranks.cmd.listranks:
    default: op
  powerranks.cmd.listsubranks:
    default: op
  powerranks.cmd.listpermissions:
    default: op
  powerranks.cmd.listplayerpermissions:
    default: op
  powerranks.cmd.checkrank:
    default: true
  powerranks.cmd.addperm:
    default: op
  powerranks.cmd.delperm:
    default: op
  powerranks.cmd.addsubrank:
    default: op
  powerranks.cmd.delsubrank:
    default: op
  powerranks.cmd.enablesubrankprefix:
    default: op
  powerranks.cmd.disablesubrankprefix:
    default: op
  powerranks.cmd.enablesubranksuffix:
    default: op
  powerranks.cmd.disablesubranksuffix:
    default: op
  powerranks.cmd.enablesubrankpermissions:
    default: op
  powerranks.cmd.disablesubrankpermissions:
    default: op
  powerranks.cmd.addsubrankworld:
    default: op
  powerranks.cmd.delsubrankworld:
    default: op
  powerranks.cmd.addinheritance:
    default: op
  powerranks.cmd.delinheritance:
    default: op
  powerranks.cmd.setprefix:
    default: op
  powerranks.cmd.setsuffix:
    default: op
  powerranks.cmd.setchatcolor:
    default: op
  powerranks.cmd.setnamecolor:
    default: op
  powerranks.cmd.createrank:
    default: op
  powerranks.cmd.deleterank:
    default: op
  powerranks.cmd.enablebuild:
    default: op
  powerranks.cmd.disablebuild:
    default: op
  powerranks.cmd.promote:
    default: op
  powerranks.cmd.demote:
    default: op
  powerranks.cmd.renamerank:
    default: op
  powerranks.cmd.setdefaultrank:
    default: op
  powerranks.cmd.factoryreset:
    default: op
  powerranks.cmd.gui:
    default: op
  powerranks.cmd.rankup:
    default: true
  powerranks.cmd.stats:
    default: op
  powerranks.cmd.addbuyablerank:
    default: op
  powerranks.cmd.delbuyablerank:
    default: op
  powerranks.cmd.setbuycost:
    default: op
  powerranks.cmd.addplayerperm:
    default: op
  powerranks.cmd.delplayerperm:
    default: op
  powerranks.cmd.createusertag:
    default: op
  powerranks.cmd.editusertag:
    default: op
  powerranks.cmd.removeusertag:
    default: op
  powerranks.cmd.setusertag.player:
    default: op
  powerranks.cmd.setusertag.admin:
    default: op
  powerranks.cmd.clearusertag.player:
    default: op
  powerranks.cmd.clearusertag.admin:
    default: op
  powerranks.cmd.listusertags:
    default: op
  powerranks.cmd.setpromoterank:
    default: op
  powerranks.cmd.setdemoterank:
    default: op
  powerranks.cmd.clearpromoterank:
    default: op
  powerranks.cmd.cleardemoterank:
    default: op
  powerranks.cmd.addoninfo:
    default: op
  powerranks.cmd.setguiicon:
    default: op
  powerranks.cmd.playerinfo:
    default: op
  powerranks.cmd.verbose:
    default: op
  powerranks.cmd.pluginhook:
    default: op
  powerranks.cmd.config:
    default: op
  powerranks.signs.create:
    default: op
  powerranks.signs.promote:
    default: op
  powerranks.signs.demote:
    default: op
  powerranks.signs.setrank:
    default: op
  powerranks.signs.checkrank:
    default: op
  powerranks.signs.gui:
    default: op
  powerranks.signs.usertag:
    default: op
  powerranks.signs.rankup:
    default: op
  powerranks.signs.admin:
    default: op